### ISSUE TITLE
Change Save Location doesn't work on Android TV

### ISSUE THREAD

**Issue by Aethix** [BiglySoftware/BiglyBT-Android#108]
I'm using an NVidia Shield Android TV device. When I select the option to change save location, it lists all of the available locations, but doesn't allow me to select any of them. Even if I highlight an option, pressing the select button does nothing and the OK button remains disabled, leaving me with no other option but to cancel out of the dialog.

**Comment by TuxPaper** [comment]
Latest version (1.2.4) should fix this, plus allow you to select any writable path
