### ISSUE TITLE
Write to external SD

### ISSUE THREAD

**Issue by adamdagan7** [BiglySoftware/BiglyBT-Android#11]
Hello,
After some extensive googling it seems that you should be able to write to external SD card (which is pretty much a must if you plan on torrenting on an android device).

The only thing is your destination folder should be `/<externalsd>/Android/data/com.biglybt.android.client`.
On that folder you should have write support.

I've installed BiglyBT on an Nvidia Shield TV, tried downloading to the above folder on a NAS share (mounted by the Shield it self - that is `/storage/.../Android/data/com.biglybt.android.client`), but keep getting permission errors on the above folder and can't get it to work.

**Comment by TuxPaper** [comment]
ooh, Nvidia Shield TV has NAS shares built in!  Unfortunately, I only have a Mi Box and a Sony Android TV to test with, and neither have a buld in NAS share feature.  I'll look around the internet though, to see if other apps have encountered this situation already.

If you have time, can you try using a thumb drive or USB drive plugged directly into your Shield TV, and see if that's working for you?  It should, but if it doesn't, then that indicates a bigger problem (for me!)

**Comment by TuxPaper** [comment]
So far the only thing I found is they didn't add writing to NAS until SHIELD Experience Upgrade 5.2.  This rolled out in June, so you probably already have it, but check anyway :)

**Comment by adamdagan7** [comment]
Hello, thanks for the quick reply.

By attaching a USB drive to the shield (mounted as removable storage), I'm indeed able to download to the drive directly.
The permission indeed works only for the specific folder (`/Android/data/com.biglybt.android.client/`).

I tried creating a share on the NAS with the correct exact path, but it didn't work.

To sum things up:

![biglybt](https://user-images.githubusercontent.com/1699998/31305855-f596ce38-ab4b-11e7-9ee1-e6393a1bf912.png)

**Comment by TuxPaper** [comment]
In case it seems like you've gone ignored, I haven't forgotten about this issue, and I appreciate the summary you gave. :)

**Comment by adamdagan7** [comment]
Did some digging of my own, it seems that specifically on the shield, the NAS write capabilities are exclusively for PLEX out of the box.
That being said, it is possible as evident on my phone, I'm just not sure what it takes.
No pressure, appreciate the reply.

**Comment by KwisatzHaderach** [comment]
I've just tried this and found out BiglyBT creates files with wrong permissions.
Even with umask 0 on the download folder the created files have permissions 600 which is apparently not enough for torrent clients, as it requires write permissions for others, not only owner user or group.
What worked for me was changing the permissions on created files to 777 (I know it's not safe, but it works) and continuing the download.

I have Nvidia Shield TV with NAS server connected.

**Comment by renom** [comment]
It is possible to write to external storage, but only to app's folder. It would be great if BiglyBT could ask for write permissions to root folder of external storage (AFAIK there's no other way to grant this permission to an app).

**Comment by vanab** [comment]
I have some problem on my SONY 65XF9005. I can download movies with a single file, but i can't download serials with subfolders. Permission denied.

**Comment by TuxPaper** [comment]
v1.3.0.2 now supports SAF and any file system or manager that implements it.  

Note that nVidia Shield's Network Storage feature is read-only, despite being listed in the default SAF folder/file chooser.  Hopefully in a future update they will implement write access.

**Comment by Shidouuu** [comment]
Apologies for bumping an old issue, but what is SAF? My save folder says "SAF Access" and I can't find anything on it

**Comment by Grafikart** [comment]
I just updated my nvidia shield and i'm encountering an issue when trying to write to the SDCard. But I have some clue that may help to solve the issue for Android 11

For other apps like VLC or Solid Explorer I can manually go to the android permission setting for the app and set file access to "always authorize"  instead of the default "Authorize if the app is opened" and it fixes the issue (I can write and read the SD card from these apps)

When I try to edit the permissions for biglyBT on android I don't have the ability to set "always authorize". A permission may be missing for biglybt (I can do a capture but my interface is in french so i'm not sure it would help)

I'm not an Android dev but I looked what changed for other apps and some seems to refer to a new permission MANAGE_EXTERNAL_STORAGE  https://github.com/videolan/vlc-android/commit/a1fa4a840359048e46b390889dc476fd1b63f55c

I hope it helps
