### ISSUE TITLE
What is "Wanted" / "Unwanted"?

### ISSUE THREAD

**Issue by galvinograd** [BiglySoftware/BiglyBT-Android#116]
Couldn't find any documentation about this feature, and couldn't figure out what it does.
Can you please tell me what it does and preferably document it?

Thanks :)

**Comment by TuxPaper** [comment]
It marks the selected file(s) as either wanted or wanted for downloading.  If you don't want the file to be downloaded, tap "Unwanted".  If you want the file to be downloaded, tap "Wanted"

**Comment by galvinograd** [comment]
But how is it different than “Stop” / “Start” funxtionality?

**Comment by TuxPaper** [comment]
Start and Stop is for the torrent.  Start connects to peers and downloads/uploads the parts of the files you want.  Stop disconnects from peers.

**Comment by auz-jsm** [comment]
**This is only a suggestion, dear developer.**

How 'bout change **wanted/unwanted** into either:
° _include/exclude_
° _regard/disregard_
° _enqueue/dequeue_
