### ISSUE TITLE
[feature request] set default file permission

### ISSUE THREAD

**Issue by CWempe** [BiglySoftware/BiglyBT-Android#117]
I am using BiglyBT inside a docker container.

The volumes where torrent files and downloads are stored are link to folders that are shared via samba.  
To edit/delete my downloads via samba I need write permission for group. (e.g. 775)

I tried setting `umask 0002` inside `.bashrc` but this seems to not affect BiglyBT.

So I get this:

```
-rw-r--r-- 1 downloader users 928670754 Apr  6 17:22 Big_Buck_Bunny_1080p_surround_FrostWire.com.avi
```

But I want this:
```
-rw-rw-r-- 1 downloader users 928670754 Apr  6 17:22 Big_Buck_Bunny_1080p_surround_FrostWire.com.avi
```

Maybe there is another way to achieve this?! Some java parameter perhaps?

Thanks

**Comment by CWempe** [comment]
Found a fix that works for me.
https://github.com/Fullaxx/ubuntu-desktop/pull/2

Feel free to close this issue if you think nobody else needs this. :)

**Comment by parg** [comment]
I love it when issues close themselves :) cheers

**Comment by TuxPaper** [comment]
Sounds like quite an adventure!  If you are ever up to creating a HowTo wiki/article, I'm sure others would benefit greatly from one.

**Comment by CWempe** [comment]
No big adventure. 😄 

Just use this image: https://hub.docker.com/r/fullaxx/biglybt

I just contributed the ideas (and some code) to let the user define a `non-root` user and the `umask` value.
