### ISSUE TITLE
CRASH: [Error Connecting] error:IllegalArgumentException: invalid core parameter: Max Upload Speed Seeding KBs.

### ISSUE THREAD

**Issue by dbareis** [BiglySoftware/BiglyBT-Android#119]
The Windows client can't be accessed by the remote while seeding (stop seeding and it works).

It will fail with a dialog titled "Error Connecting" with "log out" & "Continue" buttons and the text
"**error:IllegalArgumentException: invalid core parameter: Max Upload Speed Seeding KBs.**"

![Crash Dialog - Screenshot_20190910-134426](https://user-images.githubusercontent.com/295230/64583131-39099400-d3d3-11e9-882a-fe6b979546a0.jpg)

BiglyBT remote will hang after the "Continue" button is pressed.

This is what the Windows BiglyBT client shows (note the "**800K-600K**" bit):

![Bigly BT dies - cropped - Screenshot @ 10_09_2019 , 1_40_26 PM, D_ 0 00 k U_ 0 00 k](https://user-images.githubusercontent.com/295230/64583273-bdf4ad80-d3d3-11e9-8cc0-21ced98fad13.png)

When I stop seeding and the remote works the "**800K-600K**" bit shows as "**800K**".

Based on this I'm pretty sure I can change the client options to prevent the remote failing but I'm reporting the bug to have it fixed.

**Comment by TuxPaper** [comment]
I believe this is now fixed in the current releases of the app and the desktop client.  It's not a perfect solution as the app doesn't know about the range, but it shouldn't error out anymore.
