### ISSUE TITLE
Using magnet links doesn't work when selecting custom location

### ISSUE THREAD

**Issue by KwisatzHaderach** [BiglySoftware/BiglyBT-Android#120]
Downloading a file using a magnet link doesn't work correctly with custom location selected.
It will delete selected location and use default location set for all torrents.

**Comment by parg** [comment]
Where are you setting this custom location?

**Comment by KwisatzHaderach** [comment]
In the only  place possible, when adding a magnet link right bellow that field there is a field for adding Destination folder....so....there...

**Comment by parg** [comment]
ah, Android, sorry, I was thinking the Desktop app...
