### ISSUE TITLE
SecurityException when opening torrent using another app

### ISSUE THREAD

**Issue by TuxPaper** [BiglySoftware/BiglyBT-Android#133]
When opening a torrent in another app, such as Chrome, and choosing BiglyBT, the torrent will not open and an error will appear with something like:

* SecurityException:Permission Denial: opening provider org.chromium.chrome.browser.util.ChromeFileProvider from ProcessRecord
* SecurityException:Permission Denial: opening provider mozilla.components.feature.downloads.provider.FileProvider from ProcessRecord
* SecurityException:Permission Denial: opening provider com.android.providers.downloads.DownloadStorageProvider from ProcessRecord

Sometimes, repeating the steps in the app (ie, launching the torrent again from Chrome) will make it work.

We've only been able to reproduce it once, and could not again (yet)

Any additional  information would be helpful.

This bug seems affect most Android OS versions from v7.0 (N/API 24) and up.

It's probably something in my code that I'm not doing properly :/

**Comment by JoshuaGloriod** [comment]
Hey, old issue. But I know it's still relevant.

The app uses RC4 for encryption, are you by chance using that setting? It's 2022 and this app should not still be using that. 

https://datatracker.ietf.org/doc/html/rfc7465

All those providers? They announced they were blocking RC4 connections years ago.
