### ISSUE TITLE
Save Location Dialog (and others) can overlap system navigation bar

### ISSUE THREAD

**Issue by TuxPaper** [BiglySoftware/BiglyBT-Android#134]
On devices that have an on-screen navigation bar (the bar with home, back, etc), some dialogs overlap the buttons.

The most annoying one is the save location dialog, as the "Ok" button is often right under the "back" system button :(

**Comment by Fredo-p** [comment]
I can also confirm this.

Samsung Galaxy S8+ (SM-G995U)
Android 9
![20200402_215123](https://user-images.githubusercontent.com/5199706/78315847-2d76e980-752c-11ea-9fbe-dfea1bf721b3.jpg)

**Comment by TuxPaper** [comment]
Fixed 1.2.6
