### ISSUE TITLE
Setup issue / slow download speed on Nvidia Shield Pro

### ISSUE THREAD

**Issue by stivob** [BiglySoftware/BiglyBT-Android#146]
Hi everyone,
I am new to torrent software and I just got an Nvidia Shield Pro with an external HDD connected via USB.  I setup BiglyBT to download torrents but the download speed is very slow despite being set to unlimited.  I must have some setting incorrect.  I was able to sideload the ttorrent app on the Shield and the same exact torrent downloaded in about 30 min as opposed to an estimated time of over 4 hours via BiglyBT.  I am looking for the best software to use on the Shield that I may be able to use remotely also.  If anyone can help or point me to the right direction, I would appreciate it.  Thanks in advance!

**Comment by dbettini** [comment]
Hey, I just ended here with the same question. What did you end up using?

**Comment by stivob** [comment]
Hey, I couldn't get it to work so I downloaded the BiglyBT Mac OS app on my old MacBook and save to a hard drive connected to my Shield TV Pro.
