### ISSUE TITLE
Error adding torrent

### ISSUE THREAD

**Issue by ezromano** [BiglySoftware/BiglyBT-Android#149]
I had a lot of issues adding torrents on my Xiaomi Mi Box S, it worked temporarely when saving files to an external storage but only within the bigly files folder. All of the sudden it stopped working and now im getting an error that reads Error adding torrent: error: DownloadException: DownloadManager::addDownload: default torrent save directory must be configured while trying to add anything via the web UI.

I figured it was the write permissions on an NTFS drive, so i changed it to internal storage but that had no effect, im still getting the same error even with the external drive unplugged and the default directory set to different locations, including the biglybt folder on the internal storage and the downloads or the movies folders.

Clearing the data and reinstalling didn't help.

![1](https://user-images.githubusercontent.com/5097720/85936580-9c1cd680-b8d2-11ea-9772-132728aa54ec.png)

Edit: Stopped getting that error with the default folder configuration all of the sudden, it could just be my box that's not working properly

**Comment by TuxPaper** [comment]
v1.3 can use SAF to access SD Cards/external storage, which should help in cases like this.  Closing issue.  If you are still seeing problems, please file a new issue.
