### ISSUE TITLE
Android 8 & services

### ISSUE THREAD

**Issue by Shusshu** [BiglySoftware/BiglyBT-Android#15]
You probably already know but let's be sure about it ;)

When targeting API 26 the following is becoming a "problem" https://developer.android.com/about/versions/oreo/background.html

I checked a bit the code and currently I see a foreground service that's already great :) I think it should continue to be a foreground service as you want to let the user know he might currently be downloading a bunch of stuff
https://github.com/BiglySoftware/BiglyBT-Android/blob/5fad99bba26f6d4370a3e9d794c92f87eec9679d/BiglyBT/src/coreFlavor/java/com/biglybt/android/client/service/BiglyBTService.java#L914 

Might want to update that for Android 8... but not really mandatory

**Comment by TuxPaper** [comment]
Yeah, I don't have a v8 device, and so far I've been too lazy to set up a Virtual Device to test.

So many articles out there seem to be for people who don't want a notification, but are forced to do so.  But for a bt client, we not only want one, but need one for progress.

I've added the new Oreo Notification Channel, and I think all that's left is changing `Context.startService` to `ContextCompat.startForegroundService`

But be I'm going to have to go through the whole flow again to make sure BiglyBT core starts on a new thread that isn't linked to the main ui application, and shuts down properly. It should all work, but the odds aren't always in my favor :P

**Comment by BiglyBT** [comment]
v1.1.7 is released and has been tested on an API 26 device.  Closing as notification still shows :)
