### ISSUE TITLE
Advanced network settings reset after shutdown

### ISSUE THREAD

**Issue by headsvk** [BiglySoftware/BiglyBT-Android#157]
On Android TV when I set up advanced network settings in connection settings like this:
![Screenshot_20200714-234534](https://user-images.githubusercontent.com/7461631/87479696-38addb00-c62c-11ea-8eea-c0306db2183c.jpg)
BiglyBT pauses torrents when I disconnect from VPN as expected.

But when I restart BiglyBT, the settings are gone except one:
![Screenshot_20200714-235050](https://user-images.githubusercontent.com/7461631/87480107-ef11c000-c62c-11ea-85f1-97b72c2f1add.jpg)

Why does it reset, am I missing something?
(Screenshots from BiglyBT Android remote connected to Android TV, same settings can be seen on TV.)

**Comment by TuxPaper** [comment]
v1.3.0.2 has been released with a fix for this issue.  

Thank you for reporting, and sorry it took so long to get a release out.

**Comment by headsvk** [comment]
Hi @TuxPaper , thanks for the fix but it's partial for me. The `Bind to local IP address or interfaces` settings gets saved but not `Check bind IP addresses` nor `Enforce IP bindings`.

**Comment by TuxPaper** [comment]
Fixed in v1.3.0.8.  This time for sure, surely!
