### ISSUE TITLE
Android Gradle Flavors

### ISSUE THREAD

**Issue by Shusshu** [BiglySoftware/BiglyBT-Android#16]
More info on flavors: https://developer.android.com/studio/build/build-variants.html

Which flavors are you truly after? 
Is the following what you would like to build:

**In the current setup**
1.a Core & GA - debug
1.b Core & GA - release (store ?)
2.a Core & noGA - debug
2.b Core & noGA - release 

Do you really need those:
3.a noCore & noGA - debug
3.b noCore & noGA - release
4.a noCore & GA - debug
4.b noCore & GA - release

If I understand correctly the core is to download torrent directly on the device.
thus is the noCore still needed?

**Comment by TuxPaper** [comment]
noCore is there for two future possibilities:
1. Play store bans all bittorrent clients (in theory remote control apps would still be ok)
1. In case someone just wants to control a remote torrent client, or if we wanted to release a separate (and so much smaller) "BiglyBT Remote" app.  As an example, Vuze Remote got approved for the Amazon Store, but full Vuze (or any other full bittorrent clients) have been banned from Amazon.

the GA/noGA split is there for F-Droid, which requires FOSS.. which Google Analytics is not open source.  GA flavor is more of a "Play Services" flavor now that I've also placed the "GiveBack" subscriptions in it.

And yes, 1.b is the store release.  1.a is where I spend 90% of my time.

If only Google Play Services were FOSS.

**Comment by Shusshu** [comment]
Ok, then nothing changes :)

I have to be in 2.a as I don't have the google-services.json file
