### ISSUE TITLE
Custom rpc-url string in remote config

### ISSUE THREAD

**Issue by hathlife** [BiglySoftware/BiglyBT-Android#161]
I issue a public domain for Web management page of my transmission daemon, so I change the “rpc-url” parameter from “/transmission” to “/” ( the domain contains “transmission” string ). Currently the app only uses default "/transmission" rpc-url to connect the daemon, so I can't login. Can you add this?

**Comment by TuxPaper** [comment]
I haven't tested it, but I put a **RPC Path** in v1.3.0.8.  Setting it to blank should be what you are looking for (the '/' is prepended automatically)

![image](https://user-images.githubusercontent.com/725353/97789212-da295000-1b7b-11eb-8a73-1047741398dd.png)
