### ISSUE TITLE
[Security issue] Proxy is ignored and download proceeds without a proxy

### ISSUE THREAD

**Issue by gadelkareem** [BiglySoftware/BiglyBT-Android#166]
If you add some invalid proxy to your settings, the app will accept it and proceed to download torrents, pretending that is using the proxy.

The app should only work using the proxy if a proxy is specified.

**Comment by TuxPaper** [comment]
I think what you might be seeing is remote connections connecting to you.  If the torrent was registered to a tracker, or you had DHT on before switching the proxy on, either might still have your IP cached and be sending it to other clients.

I'll randomize the port on turning proxy on, that should prevent remote connections.  Parg just added  blocking all incoming connections if proxy is on for the beta core client, which I may try to get into the next android release.

**Comment by gadelkareem** [comment]
The connection proceeded few times after I completely shut down both the client and core. I am pretty sure there were no DHT or cached connections in memory before the download started again. My observation is that BiglyBT tried to connect through the proxy and if the connection fails, it just connects without the proxy which is huge vulnerability since a lot of users take their anonymity very seriously.

**Comment by parg** [comment]
People who take their anonymity very seriously would never, ever, consider using SOCKS.

Shutting down client + core doesn't affect cached connection information in the DHT that can persist for many hours.

**Comment by gadelkareem** [comment]
@parg I am talking about HTTP proxy.

There was no DHT connections running for hours since I just installed BiglyBT.

**Comment by parg** [comment]
HTTP proxy can't proxy peer connections, they're not HTTP

**Comment by parg** [comment]
If you want privacy look into a VPN

**Comment by gadelkareem** [comment]
I see qBittorrent can do it. Why can't BiglyBT?

![Screenshot 2020-10-16 at 12 46 20 PM](https://user-images.githubusercontent.com/1441127/96249534-99dba680-0fad-11eb-97ad-6d8fbaf13e98.png)

**Comment by parg** [comment]
https://www.downloadprivacy.com/socks-vs-http-proxy-for-torrents

**Comment by gadelkareem** [comment]
Got it! sounds like HTTP proxy is useless then.

**Comment by parg** [comment]
affirmative!

**Comment by TuxPaper** [comment]
Latest android release (1.3.0.2) now properly randomized port on enabling/disabling proxy, which effectively stops all incoming. 

However, I'll leave this bug open until next release, which will include parg's new code that blocks incoming connections when proxy is enabled.

**Comment by TuxPaper** [comment]
v1.3.0.8 now out, with core 2.5.0.1_B17, which includes blocking incoming connections when proxy is enabled.
