### ISSUE TITLE
Android Remote doesn't connect

### ISSUE THREAD

**Issue by dsbowersock** [BiglySoftware/BiglyBT-Android#187]
I've had a lot of success in the past year using the BiglyBT Android client as a remote for my desktop client.
Near the end of last year it failed to connect one day and I was unable to sort it out before I got busy and forgot.
Trying now to sort it out without success.

Currently I have a BiglyBT client running on my desktop. 
I have remote pairing enabled.
![Screenshot](https://user-images.githubusercontent.com/78646751/107118747-c105fe80-6850-11eb-8a2c-e6d757f66fdd.jpg)

I've confirmed that the pairing code I entered in BiglyBT for Android matches that of the desktop.
![Screenshot_BiglyBT](https://user-images.githubusercontent.com/78646751/107118793-0cb8a800-6851-11eb-931e-7c021742dab4.jpg)

I've been able to remotely connect to the desktop client via browser on another pc

I've tried uninstalling and reinstalling the Android app

I imagine the fix may be simple, but I can't find it.

Appreciate any help, Thanks!

**Comment by TuxPaper** [comment]
Try going to http://remote.biglybt.com on your phone, enter access code there and see if you can connect to the web ui.  If you can't, then no amount of fiddling with the app will work, and most likely your PC is not longer accessible from the internet.  In that case, check if UPnP is enabled in the 'BiglyBT Web Remote' config.  Changing the port there might help too, but will probably require restarting the client to take full effect.

It could also be the service isn't detecting your correct IP address.  If you click the 'Click to view current registration details', your desktop's browser should bring up a page which lists what it thinks your IP and port address are.  Maybe something obvious will pop up to you there.  Don't post that info here though ;)

A workaround might be to create an "Advanced Login" in the android app, which lets you enter ip/port/user/pw.  User is 'vuze' and the password is your access code.  The IP/port should be the ones listed on the page I just mentioned, or if you already know your IP, use that.  Also, if you only access your desktop remotely while on the same wifi, you might be able to use one of the "Client detected local IPv4" addresses listed on that page.

Good luck.  Firewalls, UPnP, routers, ISPs, and even virus apps all like to block your PC from being accessed, so they are probably the primary suspects.

**Comment by Ligutrino** [comment]
Same issue, I can access the client from everywhere on the web browser, but not in the app.

Best regards,

**Comment by TuxPaper** [comment]
Closing due 1.3.3 release and issue inactivity. If you are still experiencing issues, feel free to create a new issue.
