### ISSUE TITLE
"error connecting" to local ...

### ISSUE THREAD

**Issue by gintominto5329** [BiglySoftware/BiglyBT-Android#193]
![Screenshot_20210409-201002-629](https://user-images.githubusercontent.com/82209141/114197432-f671ba00-996f-11eb-9124-2286fe0401c8.png)
Hello, below is my condition:

Device: Moto G10 Power (capri-retailin),
Android SDK: 11,
Source of Application: F-Droid,
BiglyBT version: 1.3.2.0,
GMS availability: Yes,
BiglyBT Mode: Local(Run on Device),
Problem: (refer to attachment)
Last time working: Never(this was the 1st try on this device), but worked fine on another device(z2_plus) however older version,

Workaround: use an older version, 1.3.0.8(last of 2020).

Let me know if more info or logs are needed...

**Comment by lafeeverte3** [comment]
Same issue, but I'm on a Samsung S20 FE. The workaround seems to be working, thank you so much for that suggestion 🙏

**Comment by logan2k** [comment]
Another victim here, screenshot:
![biglybt](https://user-images.githubusercontent.com/79699834/126875183-1f46865a-8034-4d38-93fb-b6a685f80493.png)
Device is Amazon Fire HD8 (10th-gen,2020), OS is based on Android 9.
Big thanks to OP for your workaround, it works.

**Comment by TuxPaper** [comment]
Closing due 1.3.3 release and issue inactivity. If you are still experiencing issues, feel free to create a new issue.
