### ISSUE TITLE
[BUG] BiglyBT allocating all files from torrent

### ISSUE THREAD

**Issue by z3huti** [BiglySoftware/BiglyBT-Android#195]
BiglyBT allocating all files from torrent when I want to download just one or two files

If I add torrent from remote access, or in app self, then deselect all files in this torrent, then select one or more, BiglyBT allocating all files from this torrent and then starts to download selected one.

For every selected file, BiglyBT will start to download some 2 files also, but not all of it, some part of it.

Tested on NVIDIA Shield TV and android Phone

**Comment by parg** [comment]
see comment in chat...

[22 07:41] parg
are you sure it is allocating all files or just those 'adjacent' to the ones you have selected?
[22 07:48] parg
it is a general issue with bittorrent that parts of other files need to be downloaded because files are not aligned to piece boundaries

**Comment by z3huti** [comment]
Yes its allocating all files! Try it yourself, add torrent via remote access. Dont start torrent when adding.  Deselect all files in torrent. Select one. Start download. Watch all files been allocating.

**Comment by TuxPaper** [comment]
Closing due 1.3.3 release and issue inactivity. If you are still experiencing issues, feel free to create a new issue.

There are bug fixes in the latest release related to setting files as unwanted while torrent was active.  If you are still experiencing issues, feel free to create a new issue.
