### ISSUE TITLE
Okhttp

### ISSUE THREAD

**Issue by Shusshu** [BiglySoftware/BiglyBT-Android#2]
One thing cough my eye
```
    // We use libs/okhttp-3.5.0.jar without a HttpHeaders.class so that we
    // can overwrite it to handle a bug in the client's Vuze core.  When the
    // majority of users are on a fixed version of Vuze, we can use maven
    //compile 'com.squareup.okhttp3:okhttp:3.5.0'
    compile files('libs/okhttp-3.5.0.jar')
```

I guess now that it's BiglyBT we can upgrade to the latest okhttp ?

I'l be improving the gradle configuration in the coming days (hopefully)
Do you mind if I put a minSdk to 15 ? Nobody uses 11 to 14 and you don't really want to support 9 & 10 plus it's hardly used either https://developer.android.com/about/dashboards/index.html

**Comment by TuxPaper** [comment]
Sorry, I'd like to keep minSDK at 9 for the moment.  I plan on going to minSDK 14 soon, but I want to get a release with 9 in it out first, so older users have at least one version of the app to use.  I expect there will be a bug fix shortly afterwards.

My policy for minSDK is "don't increase it if you don't need to".  It's pretty easy to wrap things around a SDK check and @TargetAPI.  The reason for going to minSDK 14 is the new appcompat (26) requires 14.  

Same goes for okhttp, I want to get a release or two out there before switching it, so I can assess whether people are still connecting to old clients.  It's a shame I couldn't find a way to use interceptors to fixup the invalid Content-Length, but I can see why it's not possible or useful to anyone except me.  

We could always upgrade the okhttp.jar to a newer one without the HttpHeaders.class and update HttpHeaders.java, if there's some important bug fixes or optimizations they've added.

**Comment by TuxPaper** [comment]
Extra note: the project will be requiring Android Studio 3.0 beta soon (next 24 hours), as it supports Java 8, and BiglyBT's plugins are compiled to Java 8 and I'm too lazy to recompile them to J7 just for Android.

**Comment by Shusshu** [comment]
Ok, I'll wait for the next updates before doing anything

**Comment by TuxPaper** [comment]
OkHttp is now using maven central
