### ISSUE TITLE
Request for Translation

### ISSUE THREAD

**Issue by MrYKaushiK** [BiglySoftware/BiglyBT-Android#20]

**Comment by BiglyBT** [comment]
I'm not sure what language you wish to see.  We now have collaborative translations via crowdin at https://crowdin.com/project/biglybt-android

**Comment by pataquets** [comment]
@BiglyBT: I would like to request addition of Catalan language to available translation choices on Crowdin.
Also, I've added a handful of Spanish strings, thanks to your reply's link.

**Comment by TuxPaper** [comment]
I've added Catalan to the languages available in CrowdIn for BiglyBT-Android.  Please note there's also a Catalan language in BiglyBT client, which is only 76% complete.
