### ISSUE TITLE
can't stop a file from a torrent

### ISSUE THREAD

**Issue by legacychimera247** [BiglySoftware/BiglyBT-Android#200]
well i'm opening this here since it's the android github, so it's more appropriate

anyway, if i start downloading a torrent with multiple torrents in it and then i stop one of the files, generally that file just continue downloading

that would be handy when you want to free up space on your phone and just download things separately but you can't since generally partila dls (as it's written on the file) starts downloading again right after you exit the torrent menu

**Comment by TuxPaper** [comment]
There was a bug related to this that's been fixed in 1.3.3.  Torrent is now restarted when a file is marked as wanted/unwanted.
