### ISSUE TITLE
Not able to download magnets

### ISSUE THREAD

**Issue by legacychimera247** [BiglySoftware/BiglyBT-Android#203]
Unfortunately this problem arose again, libretorrent was able to download 2 out of 4 torrent immediately and the other 2 after a short while, at the same time biglybt was only able to find a torrent and was not even able to find seeders for the others

Surprisingly the pc version seems not to have this problem...

**Comment by TuxPaper** [comment]
Closing due to 1.3.3 release. If you still see this issue when running the latest version, don't hesitate to file a new issue.

**Comment by legacychimera247** [comment]
Unfortunately i changed operating system in the meantime, i am on sailfish os again, so prefer using a native client rather than an android app

needless to say anyway that if a sailfish version of biglybt would be made, would be my choice in an hearthbeat :P
