### ISSUE TITLE
Biglybt on fdroid not working at all

### ISSUE THREAD

**Issue by legacychimera247** [BiglySoftware/BiglyBT-Android#206]
Well the title says it all, tried biglybt from fdroid, but says it can't connect to the remote, even if i'm using local settings (the phone) to download things...

**Comment by asl97** [comment]
Fresh install on 1.3.1.6 and 1.3.2.0 result in "not appear to be running" error when trying to use local client.


Using 1.3.0.8 for fresh install works and get it started, no issue updating afterwards.

**Comment by TuxPaper** [comment]
F-Droid now has the latest
