### ISSUE TITLE
Refresh Settings BUG + Suggestion

### ISSUE THREAD

**Issue by dbareis** [BiglySoftware/BiglyBT-Android#208]
I have the latest Android version of the app (1.3.2.0).

The bug is that both refresh intervals are shown to apply to "mobile" and the suggestion is that dividers are added and the heading modified to make it clear what is going on.  See the two attached screenshots.

![BUG - Overview  (both say MOBILE) - Screenshot_20211210-113919](https://user-images.githubusercontent.com/295230/145504611-a92f8db7-f7d3-42c6-9e33-ee39a07ef516.jpg)

![Settings Confusing -Screenshot_20211210-121409](https://user-images.githubusercontent.com/295230/145504607-b9566560-a455-4d6d-a325-0de9ae3274d9.jpg)

**Comment by TuxPaper** [comment]
Thank You! UI bug will be fixed in next release
