### ISSUE TITLE
Write usb access

### ISSUE THREAD

**Issue by simonogru** [BiglySoftware/BiglyBT-Android#209]
Hi.
I have a TCL Android TV and I'd like torrents to be downloaded to the USB flash drive (cause the internal storage capacity is pathetic). Sadly it's labelled as "read only". FX explorer has a feature that allows me to set up "writte access" permissions for USB drive, maybe the same thing would some day be possible in your app too?

**Comment by ursoursohete** [comment]
add this function

**Comment by TuxPaper** [comment]
v1.3.3 now has improved permission support.  The USB drive may initially be listed as read-only, but selecting the USB drive row, and then clicking browse and using the system's folder chooser app should provide write access.
