### ISSUE TITLE
Unlimited time for magnet fetching

### ISSUE THREAD

**Issue by legacychimera247** [BiglySoftware/BiglyBT-Android#214]
Biglybt on the computer search for a magnet indefinitely, so if a certain file is not available at the moment, may be found later. Biglybt on android stops after a minute or so and this is very tedious, since sometime the file is 100% available but it's just biglybt having difficulties retrieving the magnet at the moment, so it would be nice to have this option...

**Comment by TuxPaper** [comment]
1.3.3 now has Magnet URIs remembered across restarts enabled by default (Settings->Full Settings->Plugins->Magnet URI Handler->Recover magnet downloads across restarts)
