### ISSUE TITLE
Can't select files if a torrent has already started

### ISSUE THREAD

**Issue by legacychimera247** [BiglySoftware/BiglyBT-Android#215]
Well if i start a torrent and want to select or unselect some files after, i cannot do that cause it's simply not working

If i deselect a file will continue downloading the same and the same for the contrary, and this bug is present since forever unfortunately

I guess it does not matter if a file is just a partial download or some pieces depend from the next file in line (or previous) cause other clients are perfectly able to do that

Hope it will be solved anyway :)

**Comment by TuxPaper** [comment]
v1.3.3 has fixed issues related to this bug, particularly around marking files as unwanted while the torrent is active (the torrent will now pause, delete the file, then start again)
