### ISSUE TITLE
Export settings doesn't work nor does proxy settings.

### ISSUE THREAD

**Issue by PROBLEMCHYLD** [BiglySoftware/BiglyBT-Android#222]
Pretty much what the title says. I tried exporting the settings which works finest but importing the exported settings did nothing. Also proxy settings doesn't work which was already reported here. Other than that good job.

**Comment by TuxPaper** [comment]
Import/Export setting is limited to the list of clients you've setup in the app. It unfortunately doesn't store the settings of the core client.

It was basically designed so that I didn't have to type in all the remote connection settings every time I re-installed the app.
