### ISSUE TITLE
F-Droid package isnt updated

### ISSUE THREAD

**Issue by Cyanide-1** [BiglySoftware/BiglyBT-Android#225]
As the title says, the F-Droid package hasn't been updated in years, and its still on an older version, it desperately needs an update. Please update it to the newest stable, thank you.

**Comment by TuxPaper** [comment]
I'll be doing a full release this month to support Android 13 (Tiramisu).  I'll do my best to remember how to add it to  F-Droid :)

**Comment by Cyanide-1** [comment]
thanks!

**Comment by TuxPaper** [comment]
F-Droid now has the latest :)
