### ISSUE TITLE
Open failed on external drive

### ISSUE THREAD

**Issue by benjamin-rota** [BiglySoftware/BiglyBT-Android#230]
Hello
Since last update I have an error on my shield tv pro : when trying to write on an external drive, an error is thrown : open failed, operation not permitted (EPERM). i checked an the app has the authorization to write on NAS in Android settings.

Any idea ?
![Screenshot_2023-09-23-13-30-39-422_com biglybt android client](https://github.com/BiglySoftware/BiglyBT-Android/assets/5030457/fae9ccd0-6589-4bb8-9096-e7a7f11b0b0f)
![Screenshot_2023-09-23-13-30-54-792_com biglybt android client](https://github.com/BiglySoftware/BiglyBT-Android/assets/5030457/28278e92-7ec6-41e3-80c6-5cc056c0a627)

**Comment by TuxPaper** [comment]
Looks like Android doesn't let you directly access that location with newer built apps.  :(

If you click the folder icon on the open torrent window, you should be able to choose the path again via the "Browse" button.  Android will ask you to give BiglyBT permissions to the folder.  You may have to stop and start the torrent to get it out of error state, or "Verify Data" which takes longer but is more thorough.

In theory, once you've approved the permissions, direct access might work again, but I'm not able to test that atm.  Which means it's probably wise to also update your default save directory in settings

**Comment by TuxPaper** [comment]
I've looked into a bit more and Android is allowing direct file creation on the NAS, but then forbids writing to the file.  The permission checks we have in place fail to pick this up, until of course, we eventually try to write to the file. 

Still looking into it

**Comment by benjamin-rota** [comment]
Thanks.
I did try to change the path, when I validate the new path Android asks for writing permission which I approved, but the error is still there.

**Comment by TuxPaper** [comment]
Current workaround for adding torrents is to set your "Default Save Location" in "Settings" to the SAF path pointing to the NAS (or wherever you want).

No workaround found yet for existing torrents.  Selecting the same path (SAF or direct) doesn't work in the current release. In theory, if the torrent is in error state, you could move the torrent data to a new folder using a file browsing app, and then change the save folder in BiglyBT to that new location.  But that's not fun and a huge hassle and error prone.

**Comment by benjamin-rota** [comment]
I may be doing something wrong but even if I set the default path in the settings and add a new torrent I get the same error.
Anyway it is very nice that you were able to reproduce the issue and answered so rapidly. BiglyBT is a very good software I love it.
Thanks

**Comment by TuxPaper** [comment]
OMG it's worse than I thought.  Android hides existing files in a folder, but lets you create new files in the same folder, all the while saying that folder is fine to access.  Which, borks existing torrents, since they exist,, but are now "hidden" except we can access them directly, but not write to them. LOL.  It's ok if you don't understand, I'm just ranting about how messed up Android is.

I have a hack fix I'm working on :)   It's still annoying because users still have to request permissions for files they once had access to, but at least it's something

**Comment by benjamin-rota** [comment]
I updated to 3.3.4 and I was able to successfully add a new torrent after changing the default save location. Android asked for permissions as expected but it worked this time.

The format of the path changed from "/storage/{drive_id}/NVIDIA_SHIELD/" to "content://com.android.externalstorage.documents/tree/{drive_id}"

**Comment by TuxPaper** [comment]
Awesome!  Access won't be as fast, but it's not too bad when writing large torrents with not that many files.

btw, the buttons on the bottom of the open torrent options dialog should now fit :)
