### ISSUE TITLE
Install 3rd-party plugin & how to translate BiglyBT Android?

### ISSUE THREAD

**Issue by Ghost-chu** [BiglySoftware/BiglyBT-Android#251]
I see that BiglyBT-Android also has a plugin system and has some cool built-in plugins. But there doesn't seem to be a way to load custom plugins?
Does this mean recompiling is the only option if I need to load my own written plugins on BiglyBT-Android.

---

I've observed that despite BiglyBT-Android having i18n support, the translated text is just “so bad that it's completely incomprehensible to the point of being completely unusable”. But I don't see a Crowdin link for BiglyBT-Android. Is there any way to participate in the translation?

**Comment by parg** [comment]
There's currently no way AFAIK of installing plugins on Android, you'd need to talk to Tux.

Regarding Crowdin - see https://crowdin.com/project/biglybt-android

**Comment by Ghost-chu** [comment]
> There's currently no way AFAIK of installing plugins on Android, you'd need to talk to Tux.
> 
> Regarding Crowdin - see https://crowdin.com/project/biglybt-android

I'm trying to modify bad translations but they all approved by "BiglyBT" user so I can't change them at all.

This has been noted by other translators, but none of us have been able to make any changes.

![image](https://github.com/user-attachments/assets/33e6efa2-31bb-43af-98a5-ee0c2e7c30fe)

**Comment by TuxPaper** [comment]
I've switched approval for the ones I could find.
I've also changed your crowdin account to Proofreader for Chinese Simplified.  Hopefully that gives you control of changing existing translations
