### ISSUE TITLE
Request: setting for default save paths

### ISSUE THREAD

**Issue by annihat** [BiglySoftware/BiglyBT-Android#36]
I've been through the settings but not yet added a torrent & I've come here looking for this setting. 
I see from another issue that this can appear in the 'save' dialogue but I would prefer somewhere I can get to without adding a new torrent. 
I categorize torrents & wish to keep the files separated by category.

**Comment by annihat** [comment]
See also #11

**Comment by TuxPaper** [comment]
v1.2.5 (just released) now has an option to set the default save path.

External SD writing (outside the private directory) is still not supported (yet!)
