### ISSUE TITLE
Support SOCKS Proxy 

### ISSUE THREAD

**Issue by TuxPaper** [BiglySoftware/BiglyBT-Android#6]
Allow setting of SOCKS Proxy for tracker and peer communications

**Comment by annihat** [comment]
+1

**Comment by Maxattax97** [comment]
+1
Tried to vote from [here](https://vote.biglybt.com/android), but I got the message:
_"You need to authorize your GitHub account in order to vote"_
even after authorizing...

**Comment by aurora-potter** [comment]
+1

**Comment by TuxPaper** [comment]
Proxy options are not available in v1.1.6
