### ISSUE TITLE
Incompatible SDK API use which may cause crash to your APP

### ISSUE THREAD

**Issue by jay2013** [BiglySoftware/BiglyBT-Android#64]
Hi BiglyBT Developers,
I develop a tool to detect incompatible SDK API use in android application. Today I use my tool to check BiglyBT downloaded from F-Droid. My tool report many bugs. Although I believe most of them are real bugs, I cannot be 100% sure because I am not very familiar with Android developing. So
please help to check it, it must be very helpful to your APP.

The attachment below is the bug report that my tool give. please help to double check!
I also really hope to get your feedback.
thank you!

**[Supplementary explanation]**
There are totally two type of bug in the report. The first one is like this: "API called in method not in [list]", the list here are sdk levels, it means your app run under these SDK version can not call API because no such API in these sdk levels.
Type two is like "API called in method no living level", it means your application can never reach this API
use, so if these API uses are not in external library, you can remove it from your own code.

APIs or methods in our report are given in signature format like "<declaringType: returnType methodName(paramTypeList)>".

And finally, the reachable path is actually one possible call stack. it is always start from dummyMainMethod which is created by our tool. So you should read it from bottom to top.

Yes, many of these bugs seem to be in third-library codes. But it do cause problems in your app. Some third-library API say that they can only be run at specific SDK Level by using "@targetapi(Build.VERSION_CODES.N)", however, Application codes tend to ignore this warning.

Donejie He
hedongjie@ict.ac.cn

[com.biglybt.android.client_19.apk.report.txt](https://github.com/BiglySoftware/BiglyBT-Android/files/1834263/com.biglybt.android.client_19.apk.report.txt)

**Comment by TuxPaper** [comment]
```
BUG: <java.util.SortedMap: java.util.Set entrySet()> called in <com.biglybt.core.util.BEncoder: boolean aV(java.lang.Object)><-1, -1>  not in [16, 17, 18, 19, 21, 22, 23, 15]
```
entrySet() is API 1 according to https://developer.android.com/reference/java/util/Map#entrySet()

```
BUG: <android.content.Context: java.lang.Object getSystemService(java.lang.String)> called in <com.biglybt.android.client.service.BiglyBTService: void K(android.content.Context)><-1, -1> no living Level
BUG: <android.app.NotificationManager: void createNotificationChannel(android.app.NotificationChannel)> called in <com.biglybt.android.client.service.BiglyBTService: void K(android.content.Context)><-1, -1> no living Level
BUG: <android.app.NotificationChannel: void setDescription(java.lang.String)> called in <com.biglybt.android.client.service.BiglyBTService: void K(android.content.Context)><-1, -1> no living Level
BUG: <android.app.NotificationChannel: void <init>(java.lang.String,java.lang.CharSequence,int)> called in <com.biglybt.android.client.service.BiglyBTService: void K(android.content.Context)><-1, -1> no living Level
```
K(android.content.Context) is [initChannels(Context context)](https://github.com/BiglySoftware/BiglyBT-Android/blob/a7d14601a718d7ca8eeba13910885052c60bbc87/BiglyBT/src/coreFlavor/java/com/biglybt/android/client/service/BiglyBTService.java#L1037) which has a `if (Build.VERSION.SDK_INT < 26) return`, but no @targetapi, I can guess why it's reported.

The remaining seem to be from 3rd party libs, except for this one which is mysterious to me:
```
BUG: <android.support.v7.app.e: void onRequestPermissionsResult(int,java.lang.String[],int[])> called in <com.biglybt.android.client.AppCompatActivityM: void onRequestPermissionsResult(int,java.lang.String[],int[])><-1, -1>  not in [16, 17, 18, 19, 21, 22, 15]
```

[com.biglybt.android.client.AppCompatActivityM: void onRequestPermissionsResult(int,java.lang.String[],int[])](https://github.com/BiglySoftware/BiglyBT-Android/blob/a52431125b4b004d20f02900622a08b58b123235/BiglyBT/src/main/java/com/biglybt/android/client/AppCompatActivityM.java#L143) is calling super, which is clearly from AppCompat (it says android.support.v7.app.e right on the BUG line), so to say it's not in [16, 17, 18, 19, 21, 22, 15] would be incorrect.
