### ISSUE TITLE
Tablet UI instead of phone UI

### ISSUE THREAD

**Issue by Darkflicker** [BiglySoftware/BiglyBT-Android#67]
It shows tablet UI with fixed sidebar on my OnePlus 3 instead of phone UI. Maybe a toggle could be added to change between both?

**Comment by TuxPaper** [comment]
v1.1.7 lets you shrink/expand by swiping.  I know it's not the perfect solution (the hamburger would be better), but it was the simplest change I could do without restructuring things.
