### ISSUE TITLE
Android 7.1.2 not visible tools in status bar (at blue line)

### ISSUE THREAD

**Issue by parg** [BiglySoftware/BiglyBT-Android#75]
See https://github.com/BiglySoftware/BiglyBT/issues/606

**Comment by bodanek** [comment]
> See [BiglySoftware/BiglyBT#606](https://github.com/BiglySoftware/BiglyBT/issues/606)

Sorry, but that is my post, or not?

**Comment by parg** [comment]
Yes - you raised the issue on the desktop product - I just cross-posted here.

**Comment by TuxPaper** [comment]
Well, that's odd.  The whole top bar shouldn't be there on Android TV.  It's currently hiding the "Actions" sidebar section.  

Probably an ugly workaround until I can release a fix, but you should be able to click the "Ok" button on the remote, when you *first* enter the screen you took a screenshot of.  The focus is probably one the Actions section header, and clicking should expand it so you can see all the actions.

**Comment by bodanek** [comment]
Hi,

I can not find your invisible "OK" ,I really play this "OK game" very long time, but without results. If you want to try it, I can give you teamviewer number to support and you can try it.

I think I need to wait to your fix.

Thank you

**Comment by bodanek** [comment]
Yes I can click OK or Enter, that is not problem, I try it.
But I can control only left panel "Sort" ; "Tag filter" and "Text filter". When I click OK or press Enter after start app, the cursor is automatically in first position "Sort" and I get expanded "Sort" menu.
There is no another Actions in these menus.
